server:
  port: 9001    #service port

eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9003/eureka}
    healthcheck:
      enabled: true

spring:
  application:
    name: order-service   #current service name to be used by the eureka server
  data:
    mongodb:
      database: order-service_db-BCJA
      port: 27017